on:
  push:
    branches:
      - '**'

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker compose config
        run: docker compose config

  integration-test:
    timeout-minutes: 10
    name: integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Start Docker Compose
        run: docker compose up -d
      - name: Wait for FastAPI to be ready
        run: |
          for i in {1..30}; do
            curl -f http://127.0.0.1:8000/healthz && break
            echo "Waiting for FastAPI..."
            sleep 2
          done
      - name: Run API Tests
        run: ./tests/api_tests.sh
      - name: Dump FastAPI logs on failure
        if: failure()
        run: docker compose logs fastapi
      - name: Shut down Docker Compose
        run: docker compose down

  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP using Workload Identity Federation
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: 'ace-wording-451920-r5'
          workload_identity_provider: 'projects/458540730021/locations/global/workloadIdentityPools/github'

      - name: Configure Docker to push to Artifact Registry
        run: gcloud auth configure-docker --quiet us-east1-docker.pkg.dev

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-east1-docker.pkg.dev/ace-wording-451920-r5/cloud-project/fastapi-server:v2
